### ISSUE TITLE
pibox-installer for linux (nightly) crash at start

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#113]
In GitLab by @Kelson42 on Aug 21, 2017, 17:22

```
$ ./pibox-installer 
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "runpy.py", line 185, in run_module
  File "runpy.py", line 85, in _run_code
  File "gui.py", line 594, in <module>
  File "gui.py", line 95, in __init__
gi._glib.GError: /tmp/_MEIDeAgWx/ui.glade:135:1 <object> requires attribute "id"
Failed to execute script __main__
```

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Aug 23, 2017, 09:59

closed via commit 881445c99fbbe83d4fc9a48c24fb410f4477a7c4
