### ISSUE TITLE
pibox-install 0.1rc5 does not start on Linux

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#129]
In GitLab by @Kelson42 on Oct 9, 2017, 20:18

```
$ ./pibox-installer 
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "runpy.py", line 185, in run_module
  File "runpy.py", line 85, in _run_code
  File "gui.py", line 615, in <module>
  File "gui.py", line 95, in __init__
gi._glib.GError: /tmp/_MEI0PJbzU/ui.glade:648:1 <object> requires attribute "id"
Failed to execute script __main__
```

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Oct 9, 2017, 20:23

closed via commit b2d4ea8a562e7efdf2af39cebaaad89545531b14

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Oct 9, 2017, 20:26

I forgot to insert id in ui.glade to be compatible with gtk3.10

Fixed

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Oct 10, 2017, 05:29

@thiolliere thx for the fix and all the nice fixes of last week.

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Oct 23, 2017, 09:22

mentioned in commit b2d4ea8a562e7efdf2af39cebaaad89545531b14
