### ISSUE TITLE
Pibox fails with windows - problem with kalite install

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#148]
In GitLab by @Kelson42 on Dec 21, 2017, 02:30

```

TASK [mook : bsf campus enable Virtual host] ***********************************
skipping: [localhost]

TASK [mook : bsf campus api enable Virtual host] *******************************
skipping: [localhost]

TASK [mook : Copy uwsgi config files] ******************************************
skipping: [localhost]

TASK [mook : Symbolic link for wsgi ini file] **********************************
skipping: [localhost]

TASK [mook : ini_file] *********************************************************
skipping: [localhost]

TASK [mook : reload ansible_local] *********************************************
skipping: [localhost]

TASK [mook : Push file to central_server] **************************************
skipping: [localhost]

TASK [mongodb : include] *******************************************************
skipping: [localhost]

TASK [mongodb : ini_file] ******************************************************
skipping: [localhost]

TASK [mongodb : reload ansible_local] ******************************************
skipping: [localhost]

TASK [mongodb : Push file to central_server] ***********************************
skipping: [localhost]

TASK [mook : include_vars] *****************************************************
skipping: [localhost]

TASK [mook : Set mook project name to have the right URL] **********************
skipping: [localhost]

TASK [mook : Set mook project name to have the right URL] **********************
skipping: [localhost]

TASK [mook : Set the central server variable for BSF Campus] *******************
skipping: [localhost]

TASK [mook : Set the central server variable for KoomBook EDU] *****************
skipping: [localhost]

TASK [mook : Configure git to avoid git clone error] ***************************
skipping: [localhost]

TASK [mook : Clone/update mook api] ********************************************
skipping: [localhost]

TASK [mook : Install specific packages] ****************************************
skipping: [localhost] => (item=[]) 

TASK [mook : Create a static dir if we are using an external hard drive] *******
skipping: [localhost]

TASK [mook : Create symlink if we are using an external hard drive] ************
skipping: [localhost]

TASK [mook : Create static dir] ************************************************
skipping: [localhost]

TASK [mook : Install python requierment] ***************************************
skipping: [localhost]

TASK [mook : Copy settings_local config files] *********************************
skipping: [localhost]

TASK [mook : add conf for KoomBook] ********************************************
skipping: [localhost]

TASK [mook : Setup startup file for uwsgi] *************************************
skipping: [localhost]

TASK [mook : Clone/update mook front] ******************************************
skipping: [localhost]

TASK [mook : Get and unarchive the vendor package] *****************************
skipping: [localhost]

TASK [mook : Copy config.js config files] **************************************
skipping: [localhost]

TASK [mook : Fix rights] *******************************************************
skipping: [localhost]

TASK [mook : Copy template for systemd mook-sync] ******************************
skipping: [localhost]

TASK [mook : Enable service] ***************************************************
skipping: [localhost]

TASK [mook : Copy vhost] *******************************************************
skipping: [localhost]

TASK [mook : Copy api vhost] ***************************************************
skipping: [localhost]

TASK [mook : bsf campus enable Virtual host] ***********************************
skipping: [localhost]

TASK [mook : bsf campus api enable Virtual host] *******************************
skipping: [localhost]

TASK [mook : Copy uwsgi config files] ******************************************
skipping: [localhost]

TASK [mook : Symbolic link for wsgi ini file] **********************************
skipping: [localhost]

TASK [mook : ini_file] *********************************************************
skipping: [localhost]

TASK [mook : reload ansible_local] *********************************************
skipping: [localhost]

TASK [mook : Push file to central_server] **************************************
skipping: [localhost]

TASK [appinventor : Install JDK package] ***************************************
skipping: [localhost]

TASK [appinventor : unarchive App Inventor] ************************************
skipping: [localhost]

TASK [appinventor : Change permissions] ****************************************
skipping: [localhost]

TASK [appinventor : Change permissions] ****************************************
skipping: [localhost]

TASK [appinventor : Setup startup file] ****************************************
skipping: [localhost]

TASK [appinventor : Copy nginx vhost] ******************************************
skipping: [localhost]

TASK [appinventor : Nginx enable Virtual host] *********************************
skipping: [localhost]

TASK [appinventor : Enable service AppInventor] ********************************
skipping: [localhost]

TASK [appinventor : ini_file] **************************************************
skipping: [localhost]

TASK [appinventor : reload ansible_local] **************************************
skipping: [localhost]

TASK [appinventor : Push file to central_server] *******************************
skipping: [localhost]

TASK [kalite : include_vars] ***************************************************
ok: [localhost]

TASK [kalite : Ensure kalite is stopped if service exist] **********************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'kalite'\": "}
...ignoring

TASK [kalite : Create a working dir Kalite] ************************************
changed: [localhost]

TASK [kalite : Install Ka-lite] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/home/ideascube/.kalite/env/bin/pip2 install ka-lite==0.16.9", "failed": true, "msg": "stdout: New python executable in /home/ideascube/.kalite/env/bin/python2\nAlso creating executable in /home/ideascube/.kalite/env/bin/python\nInstalling setuptools, pip...done.\nRunning virtualenv with interpreter /usr/bin/python2\nDownloading/unpacking ka-lite==0.16.9\n  Running setup.py (path:/tmp/pip-build-KWSh33/ka-lite/setup.py) egg_info for package ka-lite\n    Already blocking...\n    Already blocking...\n    \n    warning: no previously-included files matching '*' found under directory 'kalite/database'\n    warning: no previously-included files matching '*' found under directory 'kalite/static'\n    warning: no previously-included files matching '*' found under directory 'data/khan'\n    warning: no previously-included files matching '*pyc' found under directory 'python-packages'\n    warning: no files found matching '*' under directory 'dist-packages'\nDownloading/unpacking docopt>=0.6,<0.7 (from ka-lite==0.16.9)\n  Downloading docopt-0.6.2.tar.gz\n  Running setup.py (path:/tmp/pip-build-KWSh33/docopt/setup.py) egg_info for package docopt\n    \nDownloading/unpacking South==0.8.4 (from ka-lite==0.16.9)\nDownloading/unpacking django-js-reverse==0.5.0 (from ka-lite==0.16.9)\n  Downloading django_js_reverse-0.5.0-py2.py3-none-any.whl\nDownloading/unpacking ply==3.4 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-KWSh33/ply/setup.py) egg_info for package ply\n    \nDownloading/unpacking slimit==0.8.1 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-KWSh33/slimit/setup.py) egg_info for package slimit\n    \nDownloading/unpacking six==1.9.0 (from ka-lite==0.16.9)\n  Downloading six-1.9.0-py2.py3-none-any.whl\nDownloading/unpacking django-appconf==1.0.1 (from ka-lite==0.16.9)\n  Downloading django_appconf-1.0.1-py2.py3-none-any.whl\nDownloading/unpacking peewee==2.6.4 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-KWSh33/peewee/setup.py) egg_info for package peewee\n    \nDownloading/unpacking python-dateutil==2.4.2 (from ka-lite==0.16.9)\nDownloading/unpacking django-dbbackup==2.3.2 (from ka-lite==0.16.9)\n  Downloading django-dbbackup-2.3.2.tar.gz\n  Running setup.py (path:/tmp/pip-build-KWSh33/django-dbbackup/setup.py) egg_info for package django-dbbackup\n    \nDownloading/unpacking ifcfg==0.9.3 (from ka-lite==0.16.9)\n  Downloading ifcfg-0.9.3-py2-none-any.whl\nDownloading/unpacking requests==1.1.0 (from ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-KWSh33/requests/setup.py) egg_info for package requests\n    \nDownloading/unpacking Django>=1.5 (from django-js-reverse==0.5.0->ka-lite==0.16.9)\n  Running setup.py (path:/tmp/pip-build-KWSh33/Django/setup.py) egg_info for package Django\n    Traceback (most recent call last):\n      File \"<string>\", line 17, in <module>\n      File \"/tmp/pip-build-KWSh33/Django/setup.py\", line 32, in <module>\n        version = __import__('django').get_version()\n      File \"django/__init__.py\", line 1, in <module>\n        from django.utils.version import get_version\n      File \"django/utils/version.py\", line 61, in <module>\n        @functools.lru_cache()\n    AttributeError: 'module' object has no attribute 'lru_cache'\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n\n  File \"<string>\", line 17, in <module>\n\n  File \"/tmp/pip-build-KWSh33/Django/setup.py\", line 32, in <module>\n\n    version = __import__('django').get_version()\n\n  File \"django/__init__.py\", line 1, in <module>\n\n    from django.utils.version import get_version\n\n  File \"django/utils/version.py\", line 61, in <module>\n\n    @functools.lru_cache()\n\nAttributeError: 'module' object has no attribute 'lru_cache'\n\n----------------------------------------\nCleaning up...\nCommand python setup.py egg_info failed with error code 1 in /tmp/pip-build-KWSh33/Django\nStoring debug log for failure in /root/.pip/pip.log\n"}

RUNNING HANDLER [system : update timezone] *************************************

RUNNING HANDLER [nginx : restart nginx] ****************************************

RUNNING HANDLER [hostapd : restart hostapd] ************************************

RUNNING HANDLER [network-manager : restart dnsmasq] ****************************

RUNNING HANDLER [ideascube : restart uwsgi] ************************************

RUNNING HANDLER [kiwix : restart kiwix] ****************************************
	to retry, use: --limit @/var/lib/ansible/local/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=157  changed=111  unreachable=0    failed=1   

STDERR:  [WARNING]: Consider using apt module rather than running apt-get
sudo shutdown 0
STDERR: Shutdown scheduled for Wed 2017-12-20 23:20:15 CET, use 'shutdown -c' to cancel.
Failed
ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook --inventory hosts --tags master,custom --extra-vars "ideascube_project_name=pibox timezone=Europe/Berlin git_branch=oneUpdateFile0.3 own_config_file=True managed_by_bsf=False" main.yml'

```

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Dec 21, 2017, 12:09

install kalite formatted message:
```
fatal: [localhost]: FAILED! => {
	"changed": false,
	"cmd": "/home/ideascube/.kalite/env/bin/pip2 install ka-lite==0.16.9",
	"failed": true,
	"msg":

stdout: New python executable in /home/ideascube/.kalite/env/bin/python2
Also creating executable in /home/ideascube/.kalite/env/bin/python
Installing setuptools, pip...done.
Running virtualenv with interpreter /usr/bin/python2
Downloading/unpacking ka-lite==0.16.9
  Running setup.py (path:/tmp/pip-build-KWSh33/ka-lite/setup.py) egg_info for package ka-lite
    Already blocking...
    Already blocking...
    
    warning: no previously-included files matching '*' found under directory 'kalite/database'
    warning: no previously-included files matching '*' found under directory 'kalite/static'
    warning: no previously-included files matching '*' found under directory 'data/khan'
    warning: no previously-included files matching '*pyc' found under directory 'python-packages'
    warning: no files found matching '*' under directory 'dist-packages'
Downloading/unpacking docopt>=0.6,<0.7 (from ka-lite==0.16.9)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py (path:/tmp/pip-build-KWSh33/docopt/setup.py) egg_info for package docopt
    
Downloading/unpacking South==0.8.4 (from ka-lite==0.16.9)
Downloading/unpacking django-js-reverse==0.5.0 (from ka-lite==0.16.9)
  Downloading django_js_reverse-0.5.0-py2.py3-none-any.whl
Downloading/unpacking ply==3.4 (from ka-lite==0.16.9)
  Running setup.py (path:/tmp/pip-build-KWSh33/ply/setup.py) egg_info for package ply
    
Downloading/unpacking slimit==0.8.1 (from ka-lite==0.16.9)
  Running setup.py (path:/tmp/pip-build-KWSh33/slimit/setup.py) egg_info for package slimit
    
Downloading/unpacking six==1.9.0 (from ka-lite==0.16.9)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking django-appconf==1.0.1 (from ka-lite==0.16.9)
  Downloading django_appconf-1.0.1-py2.py3-none-any.whl
Downloading/unpacking peewee==2.6.4 (from ka-lite==0.16.9)
  Running setup.py (path:/tmp/pip-build-KWSh33/peewee/setup.py) egg_info for package peewee
    
Downloading/unpacking python-dateutil==2.4.2 (from ka-lite==0.16.9)
Downloading/unpacking django-dbbackup==2.3.2 (from ka-lite==0.16.9)
  Downloading django-dbbackup-2.3.2.tar.gz
  Running setup.py (path:/tmp/pip-build-KWSh33/django-dbbackup/setup.py) egg_info for package django-dbbackup
    
Downloading/unpacking ifcfg==0.9.3 (from ka-lite==0.16.9)
  Downloading ifcfg-0.9.3-py2-none-any.whl
Downloading/unpacking requests==1.1.0 (from ka-lite==0.16.9)
  Running setup.py (path:/tmp/pip-build-KWSh33/requests/setup.py) egg_info for package requests
    
Downloading/unpacking Django>=1.5 (from django-js-reverse==0.5.0->ka-lite==0.16.9)
  Running setup.py (path:/tmp/pip-build-KWSh33/Django/setup.py) egg_info for package Django
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-KWSh33/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-KWSh33/Django/setup.py", line 32, in <module>

    version = __import__('django').get_version()

  File "django/__init__.py", line 1, in <module>

    from django.utils.version import get_version

  File "django/utils/version.py", line 61, in <module>

    @functools.lru_cache()

AttributeError: 'module' object has no attribute 'lru_cache'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-KWSh33/Django
Storing debug log for failure in /root/.pip/pip.log

}
```

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Dec 21, 2017, 20:43

this must be solve by https://framagit.org/ideascube/ansiblecube/merge_requests/1

it was because kalite tries to install django2 to fullfill its requirements but django fails to install with python2 because it is not supported.

I'm actually very surprised that kalite requirements are not using semver.

I'll relaunch builds on CI it should be ready to test again in an hour. I'll probably do one tonight

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Dec 21, 2017, 20:51

but the fix should be in kalite requirements to have Django>=1.5<2

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Dec 22, 2017, 08:31

@thiolliere Thx, does it mean the last nightly is OK?

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Dec 22, 2017, 09:50

Yes and I made a successful image build with kalite last night.

Also todays build are the same.

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Dec 22, 2017, 10:04

closed

**Comment by rgaudin** [comment]
In GitLab by @benjaoming on Dec 22, 2017, 12:06

Hi fellow devs!

I'm a KA Lite developer.

The distribution called `ka-lite` on PyPi has dependencies and was intended to be used in a dynamic kind of environment.. with other Python applications.

However, please use `ka-lite-static` instead where all dependencies are bundled inside KA Lite's own path.

Explanations:

https://github.com/ideascube/ansiblecube/pull/155#issuecomment-350038332

Also fixed in IIAB:

https://github.com/iiab/iiab/pull/495

**Comment by rgaudin** [comment]
In GitLab by @benjaoming on Dec 22, 2017, 21:12

FYI: KA Lite 0.17.4 has just been released on PyPi. Release notes are here: http://ka-lite.readthedocs.io/en/0.17.x/installguide/release_notes.html

You might consider especially the new project setting `KALITE_WELCOME_MESSAGE`
