### ISSUE TITLE
Unable to choose content in last nightly build

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#24]
In GitLab by @Kelson42 on Jun 30, 2017, 05:35

Traceback (most recent call last):
  File "gui.py", line 183, in zim_choose_content_button_clicked
  File "gui.py", line 318, in __init__
NameError: name 'DATA_DIR' is not defined

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jun 30, 2017, 08:08

mentioned in commit 8fbea7263fc5821c2ea9742b6353c76f2a4dd5a8

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jun 30, 2017, 08:09

This is fixed

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jun 30, 2017, 08:09

closed
