### ISSUE TITLE
New fail scenario on macos with rc6

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#247]
In GitLab by @Kelson42 on Sep 11, 2018, 15:32

```
[STAGE 0/6: Preparations - 0%]
[STAGE 0/6: Preparations - 0%]
--> Check System Requirements
Please read https://framagit.org/ideascube/pibox-installer/wikis/System-Requirements for details
--> Ensure user files are present
--> Prepare Image file
--> Change SD-card device mode (/dev/disk7)
Call: ['diskutil', 'unmountDisk', '/dev/disk7']
Unmount of all volumes on disk7 was successful

Call: ['/usr/bin/osascript', '-e', 'do shell script "chmod -v o+rw /dev/disk7 2>&1" with administrator privileges']
/dev/disk7

[STAGE 1/6: Retrieve Master Image - 0%]
--> Retrieving base image file
[                                                          ] 0%
[                                                          ] 1%
[.                                                         ] 1%
[.                                                         ] 2%
[.                                                         ] 3%
[..                                                        ] 3%
[..                                                        ] 4%
[..                                                        ] 5%
[...                                                       ] 5%
[...                                                       ] 6%
[....                                                      ] 6%
[....                                                      ] 7%
[....                                                      ] 8%
[.....                                                     ] 8%
[.....                                                     ] 9%
[.....                                                     ] 10%
[......                                                    ] 10%
[......                                                    ] 11%
[......                                                    ] 12%
[.......                                                   ] 12%
[.......                                                   ] 13%
[........                                                  ] 13%
[........                                                  ] 14%
[........                                                  ] 15%
[.........                                                 ] 15%
[.........                                                 ] 16%
[.........                                                 ] 17%
[..........                                                ] 17%
[..........                                                ] 18%
[...........                                               ] 18%
[...........                                               ] 19%
[...........                                               ] 20%
[............                                              ] 20%
[............                                              ] 21%
[............                                              ] 22%
[.............                                             ] 22%
[.............                                             ] 23%
[.............                                             ] 24%
[..............                                            ] 24%
[..............                                            ] 25%
[...............                                           ] 25%
[...............                                           ] 26%
[...............                                           ] 27%
[................                                          ] 27%
[................                                          ] 28%
[................                                          ] 29%
[.................                                         ] 29%
[.................                                         ] 30%
[.................                                         ] 31%
[..................                                        ] 31%
[..................                                        ] 32%
[...................                                       ] 32%
[...................                                       ] 33%
[...................                                       ] 34%
[....................                                      ] 34%
[....................                                      ] 35%
[....................                                      ] 36%
[.....................                                     ] 36%
[.....................                                     ] 37%
[......................                                    ] 37%
[......................                                    ] 38%
[......................                                    ] 39%
[.......................                                   ] 39%
[.......................                                   ] 40%
[.......................                                   ] 41%
[........................                                  ] 41%
[........................                                  ] 42%
[........................                                  ] 43%
[.........................                                 ] 43%
[.........................                                 ] 44%
[..........................                                ] 44%
[..........................                                ] 45%
[..........................                                ] 46%
[...........................                               ] 46%
[...........................                               ] 47%
[...........................                               ] 48%
[............................                              ] 48%
[............................                              ] 49%
[.............................                             ] 50%
[.............................                             ] 51%
[..............................                            ] 51%
[..............................                            ] 52%
[..............................                            ] 53%
[...............................                           ] 53%
[...............................                           ] 54%
[...............................                           ] 55%
[................................                          ] 55%
[................................                          ] 56%
[.................................                         ] 56%
[.................................                         ] 57%
[.................................                         ] 58%
[..................................                        ] 58%
[..................................                        ] 59%
[..................................                        ] 60%
[...................................                       ] 60%
[...................................                       ] 61%
[...................................                       ] 62%
[....................................                      ] 62%
[....................................                      ] 63%
[.....................................                     ] 63%
[.....................................                     ] 64%
[.....................................                     ] 65%
[......................................                    ] 65%
[......................................                    ] 66%
[......................................                    ] 67%
[.......................................                   ] 67%
[.......................................                   ] 68%
[........................................                  ] 68%
[........................................                  ] 69%
[........................................                  ] 70%
[.........................................                 ] 70%
[.........................................                 ] 71%
[.........................................                 ] 72%
[..........................................                ] 72%
[..........................................                ] 73%
[..........................................                ] 74%
[...........................................               ] 74%
[...........................................               ] 75%
[............................................              ] 75%
[............................................              ] 76%
[............................................              ] 77%
[.............................................             ] 77%
[.............................................             ] 78%
[.............................................             ] 79%
[..............................................            ] 79%
[..............................................            ] 80%
[..............................................            ] 81%
[...............................................           ] 81%
[...............................................           ] 82%
[................................................          ] 82%
[................................................          ] 83%
[................................................          ] 84%
[.................................................         ] 84%
[.................................................         ] 85%
[.................................................         ] 86%
[..................................................        ] 86%
[..................................................        ] 87%
[...................................................       ] 87%
[...................................................       ] 88%
[...................................................       ] 89%
[....................................................      ] 89%
[....................................................      ] 90%
[....................................................      ] 91%
[.....................................................     ] 91%
[.....................................................     ] 92%
[.....................................................     ] 93%
[......................................................    ] 93%
[......................................................    ] 94%
[.......................................................   ] 94%
[.......................................................   ] 95%
[.......................................................   ] 96%
[........................................................  ] 96%
[........................................................  ] 97%
[........................................................  ] 98%
[......................................................... ] 98%
[......................................................... ] 99%
[..........................................................] 100%

[STAGE 1/6: Retrieve Master Image - 8%]
--> Extracting base image from ZIP file
Extraction complete: /Volumes/Untitled/plug-2018_09_09-08_39_10.BUILDING.img
[STAGE 1/6: Retrieve Master Image - 15%]
--> Testing mount procedure
Call: ['/usr/bin/hdiutil', 'attach', '-nomount', '/Volumes/Untitled/plug-2018_09_09-08_39_10.BUILDING.img']
/dev/disk8          	FDisk_partition_scheme         	

/dev/disk8s1        	Windows_FAT_32                 	

/dev/disk8s2        	Linux                          	

/dev/disk8s3        	Windows_NTFS                   	

Call: ['/sbin/mount', '-t', 'exfat', '/dev/disk8s3', '/var/folders/s7/frvr3wkd3_34_kkd353f70k40000gn/T/tmp_49azmmt']
Call: ['/sbin/umount', '/var/folders/s7/frvr3wkd3_34_kkd353f70k40000gn/T/tmp_49azmmt']
Call: ['/usr/bin/hdiutil', 'detach', '/dev/disk8']
"disk8" unmounted.

"disk8" ejected.

Call: ['/usr/bin/hdiutil', 'attach', '-nomount', '/Volumes/Untitled/plug-2018_09_09-08_39_10.BUILDING.img']
/dev/disk8          	FDisk_partition_scheme         	

/dev/disk8s1        	Windows_FAT_32                 	

/dev/disk8s2        	Linux                          	

/dev/disk8s3        	Windows_NTFS                   	

Call: ['/sbin/mount', '-t', 'exfat', '/dev/disk8s3', '/var/folders/s7/frvr3wkd3_34_kkd353f70k40000gn/T/tmp8p7xl3kn']
Call: ['/sbin/umount', '/var/folders/s7/frvr3wkd3_34_kkd353f70k40000gn/T/tmp8p7xl3kn']
Call: ['/usr/bin/hdiutil', 'detach', '/dev/disk8']
"disk8" unmounted.

"disk8" ejected.

[STAGE 2/6: Download contents - 17%]
--> Starting all content downloads
--> Retrieving resources_en_fr_2018-08.zip (970.56 MiB)
Reusing already downloaded /Volumes/Untitled/cache/resources_en_fr_2018-08.zip
[STAGE 2/6: Download contents - 17%]
--> Retrieving package_wikipedia_fr_medicine_nopic.fr-2018-07-04.zim (77.43 MiB)
calculating sum for /Volumes/Untitled/cache/package_wikipedia_fr_medicine_nopic.fr-2018-07-04.zim...MATCH.
Reusing already downloaded /Volumes/Untitled/cache/package_wikipedia_fr_medicine_nopic.fr-2018-07-04.zim
[STAGE 2/6: Download contents - 17%]
--> Retrieving package_vikidia_fr_all.fr-2018-07-02.zim (670.43 MiB)
calculating sum for /Volumes/Untitled/cache/package_vikidia_fr_all.fr-2018-07-02.zim...MATCH.
Reusing already downloaded /Volumes/Untitled/cache/package_vikidia_fr_all.fr-2018-07-02.zim
[STAGE 2/6: Download contents - 17%]
--> Retrieving package_wikimooc_fr_all.fr-2018-06-22.zim (613.07 MiB)
calculating sum for /Volumes/Untitled/cache/package_wikimooc_fr_all.fr-2018-06-22.zim...MATCH.
Reusing already downloaded /Volumes/Untitled/cache/package_wikimooc_fr_all.fr-2018-06-22.zim
[STAGE 2/6: Download contents - 17%]
--> Retrieving package_wikipedia_fr_all_novid.fr-2018-06-16.zim (28.54 GiB)
calculating sum for /Volumes/Untitled/cache/package_wikipedia_fr_all_novid.fr-2018-06-16.zim...MISMATCH.
[                                                          ] 0%
[                                                          ] 1%
[.                                                         ] 1%
[.                                                         ] 2%
[.                                                         ] 3%
[..                                                        ] 3%
[..                                                        ] 4%
[..                                                        ] 5%
[...                                                       ] 5%
[...                                                       ] 6%
[....                                                      ] 6%
[....                                                      ] 7%
[....                                                      ] 8%
[.....                                                     ] 8%
[.....                                                     ] 9%
[.....                                                     ] 10%
[......                                                    ] 10%
[......                                                    ] 11%
[......                                                    ] 12%
[.......                                                   ] 12%
[.......                                                   ] 13%
[........                                                  ] 13%
[........                                                  ] 14%
[........                                                  ] 15%
[.........                                                 ] 15%
[.........                                                 ] 16%
[.........                                                 ] 17%
[..........                                                ] 17%
[..........                                                ] 18%
[...........                                               ] 18%
[...........                                               ] 19%
[...........                                               ] 20%
[............                                              ] 20%
[............                                              ] 21%
[............                                              ] 22%
[.............                                             ] 22%
[.............                                             ] 23%
[.............                                             ] 24%
[..............                                            ] 24%
[..............                                            ] 25%
[...............                                           ] 25%
[...............                                           ] 26%
[...............                                           ] 27%
[................                                          ] 27%
[................                                          ] 28%
[................                                          ] 29%
[.................                                         ] 29%
[.................                                         ] 30%
[.................                                         ] 31%
[..................                                        ] 31%
[..................                                        ] 32%
[...................                                       ] 32%
[...................                                       ] 33%
[...................                                       ] 34%
[....................                                      ] 34%
[....................                                      ] 35%
[....................                                      ] 36%
[.....................                                     ] 36%
[.....................                                     ] 37%
[......................                                    ] 37%
[......................                                    ] 38%
[......................                                    ] 39%
[.......................                                   ] 39%
[.......................                                   ] 40%
[.......................                                   ] 41%
[........................                                  ] 41%
[........................                                  ] 42%
[........................                                  ] 43%
[.........................                                 ] 43%
[.........................                                 ] 44%
[..........................                                ] 44%
[..........................                                ] 45%
[..........................                                ] 46%
[...........................                               ] 46%
[...........................                               ] 47%
[...........................                               ] 48%
[............................                              ] 48%
[............................                              ] 49%
[.............................                             ] 50%
[.............................                             ] 51%
[..............................                            ] 51%
[..............................                            ] 52%
[..............................                            ] 53%
[...............................                           ] 53%
[...............................                           ] 54%
[...............................                           ] 55%
[................................                          ] 55%
[................................                          ] 56%
[.................................                         ] 56%
[.................................                         ] 57%
[.................................                         ] 58%
[..................................                        ] 58%
[..................................                        ] 59%
[..................................                        ] 60%
[...................................                       ] 60%
[...................................                       ] 61%
[...................................                       ] 62%
[....................................                      ] 62%
[....................................                      ] 63%
[.....................................                     ] 63%
[.....................................                     ] 64%
[.....................................                     ] 65%
[......................................                    ] 65%
[......................................                    ] 66%
[......................................                    ] 67%
[.......................................                   ] 67%
[.......................................                   ] 68%
[........................................                  ] 68%
[........................................                  ] 69%
[........................................                  ] 70%
[.........................................                 ] 70%
[.........................................                 ] 71%
[.........................................                 ] 72%
[..........................................                ] 72%
[..........................................                ] 73%
[..........................................                ] 74%
[...........................................               ] 74%
[...........................................               ] 75%
[............................................              ] 75%
[............................................              ] 76%
[............................................              ] 77%
[.............................................             ] 77%
[.............................................             ] 78%
[.............................................             ] 79%
[..............................................            ] 79%
[..............................................            ] 80%
[..............................................            ] 81%
[...............................................           ] 81%
[...............................................           ] 82%
[................................................          ] 82%
[................................................          ] 83%
[................................................          ] 84%
[.................................................         ] 84%
[.................................................         ] 85%
[.................................................         ] 86%
[..................................................        ] 86%
[..................................................        ] 87%
[...................................................       ] 87%
[...................................................       ] 88%
[...................................................       ] 89%
[....................................................      ] 89%
[....................................................      ] 90%
[....................................................      ] 91%
[.....................................................     ] 91%
[.....................................................     ] 92%
[.....................................................     ] 93%
[......................................................    ] 93%
[......................................................    ] 94%
[.......................................................   ] 94%
[.......................................................   ] 95%
[.......................................................   ] 96%
[........................................................  ] 96%
[........................................................  ] 97%
[........................................................  ] 98%
[......................................................... ] 98%
[......................................................... ] 99%
[..........................................................] 100%

Saved `package_wikipedia_fr_all_novid.fr-2018-06-16.zim` successfuly: 28.54 GiB
[STAGE 2/6: Download contents - 27%]
--> Retrieving package_wikiquote_fr_all_novid.fr-2018-06-17.zim (52.48 MiB)
[                                                          ] 0%
[                                                          ] 1%
[.                                                         ] 1%
[.                                                         ] 2%
[.                                                         ] 3%
[..                                                        ] 3%
[..                                                        ] 4%
[..                                                        ] 5%
[...                                                       ] 5%
[...                                                       ] 6%
[....                                                      ] 6%
[....                                                      ] 7%
[....                                                      ] 8%
[.....                                                     ] 8%
[.....                                                     ] 9%
[.....                                                     ] 10%
[......                                                    ] 10%
[......                                                    ] 11%
[......                                                    ] 12%
[.......                                                   ] 12%
[.......                                                   ] 13%
[........                                                  ] 13%
[........                                                  ] 14%
[........                                                  ] 15%
[.........                                                 ] 15%
[.........                                                 ] 16%
[.........                                                 ] 17%
[..........                                                ] 17%
[..........                                                ] 18%
[...........                                               ] 18%
[...........                                               ] 19%
[...........                                               ] 20%
[............                                              ] 20%
[............                                              ] 21%
[............                                              ] 22%
[.............                                             ] 22%
[.............                                             ] 23%
[.............                                             ] 24%
[..............                                            ] 24%
[..............                                            ] 25%
[...............                                           ] 25%
[...............                                           ] 26%
[...............                                           ] 27%
[................                                          ] 27%
[................                                          ] 28%
[................                                          ] 29%
[.................                                         ] 29%
[.................                                         ] 30%
[.................                                         ] 31%
[..................                                        ] 31%
[..................                                        ] 32%
[...................                                       ] 32%
[...................                                       ] 33%
[...................                                       ] 34%
[....................                                      ] 34%
[....................                                      ] 35%
[....................                                      ] 36%
[.....................                                     ] 36%
[.....................                                     ] 37%
[......................                                    ] 37%
[......................                                    ] 38%
[......................                                    ] 39%
[.......................                                   ] 39%
[.......................                                   ] 40%
[.......................                                   ] 41%
[........................                                  ] 41%
[........................                                  ] 42%
[........................                                  ] 43%
[.........................                                 ] 43%
[.........................                                 ] 44%
[..........................                                ] 44%
[..........................                                ] 45%
[..........................                                ] 46%
[...........................                               ] 46%
[...........................                               ] 47%
[...........................                               ] 48%
[............................                              ] 48%
[............................                              ] 49%
[.............................                             ] 50%
[.............................                             ] 51%
[..............................                            ] 51%
[..............................                            ] 52%
[..............................                            ] 53%
[...............................                           ] 53%
[...............................                           ] 54%
[...............................                           ] 55%
[................................                          ] 55%
[................................                          ] 56%
[.................................                         ] 56%
[.................................                         ] 57%
[.................................                         ] 58%
[..................................                        ] 58%
[..................................                        ] 59%
[..................................                        ] 60%
[...................................                       ] 60%
[...................................                       ] 61%
[...................................                       ] 62%
[....................................                      ] 62%
[....................................                      ] 63%
[.....................................                     ] 63%
[.....................................                     ] 64%
[.....................................                     ] 65%
[......................................                    ] 65%
[......................................                    ] 66%
[......................................                    ] 67%
[.......................................                   ] 67%
[.......................................                   ] 68%
[........................................                  ] 68%
[........................................                  ] 69%
[........................................                  ] 70%
[.........................................                 ] 70%
[.........................................                 ] 71%
[.........................................                 ] 72%
[..........................................                ] 72%
[..........................................                ] 73%
[..........................................                ] 74%
[...........................................               ] 74%
[...........................................               ] 75%
[............................................              ] 75%
[............................................              ] 76%
[............................................              ] 77%
[.............................................             ] 77%
[.............................................             ] 78%
[.............................................             ] 79%
[..............................................            ] 79%
[..............................................            ] 80%
[..............................................            ] 81%
[...............................................           ] 81%
[...............................................           ] 82%
[................................................          ] 82%
[................................................          ] 83%
[................................................          ] 84%
[.................................................         ] 84%
[.................................................         ] 85%
[.................................................         ] 86%
[..................................................        ] 86%
[..................................................        ] 87%
[...................................................       ] 87%
[...................................................       ] 88%
[...................................................       ] 89%
[....................................................      ] 89%
[....................................................      ] 90%
[....................................................      ] 91%
[.....................................................     ] 91%
[.....................................................     ] 92%
[.....................................................     ] 93%
[......................................................    ] 93%
[......................................................    ] 94%
[.......................................................   ] 94%
[.......................................................   ] 95%
[.......................................................   ] 96%
[........................................................  ] 96%
[........................................................  ] 97%
[........................................................  ] 98%
[......................................................... ] 98%
[......................................................... ] 99%
[..........................................................] 100%

Saved `package_wikiquote_fr_all_novid.fr-2018-06-17.zim` successfuly: 52.48 MiB
[STAGE 2/6: Download contents - 28%]
--> Retrieving package_wikisource_fr_all_novid.fr-2018-06-18.zim (10.22 GiB)
[                                                          ] 0%
[                                                          ] 1%
[.                                                         ] 1%
[.                                                         ] 2%
[.                                                         ] 3%
[..                                                        ] 3%
[..                                                        ] 4%
[..                                                        ] 5%
[...                                                       ] 5%
[...                                                       ] 6%
[....                                                      ] 6%
[....                                                      ] 7%
[....                                                      ] 8%
[.....                                                     ] 8%
[.....                                                     ] 9%
[.....                                                     ] 10%
[......                                                    ] 10%
[......                                                    ] 11%
[......                                                    ] 12%
[.......                                                   ] 12%
[.......                                                   ] 13%
[........                                                  ] 13%
[........                                                  ] 14%
[........                                                  ] 15%
[.........                                                 ] 15%
[.........                                                 ] 16%
[.........                                                 ] 17%
[..........                                                ] 17%
Error downloading http://download.kiwix.org/zim/wikisource/wikisource_fr_all_novid_2018-06.zim to /Volumes/Untitled/cache/package_wikisource_fr_all_novid.fr-2018-06-18.zim
("Connection broken: OSError(65, 'No route to host')", OSError(65, 'No route to host'))

--- Exception Trace ---
Traceback (most recent call last):
  File "urllib3/response.py", line 302, in _error_catcher
  File "urllib3/response.py", line 384, in read
  File "http/client.py", line 449, in read
  File "http/client.py", line 493, in readinto
  File "socket.py", line 586, in readinto
  File "ssl.py", line 1009, in recv_into
  File "ssl.py", line 871, in read
  File "ssl.py", line 631, in read
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/models.py", line 745, in generate
  File "urllib3/response.py", line 436, in stream
  File "urllib3/response.py", line 401, in read
  File "contextlib.py", line 99, in __exit__
  File "urllib3/response.py", line 320, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: OSError(65, 'No route to host')", OSError(65, 'No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_installation.py", line 155, in run_installation
  File "backend/download.py", line 131, in download_file
  File "backend/download.py", line 110, in stream
  File "requests/models.py", line 748, in generate
requests.exceptions.ChunkedEncodingError: ("Connection broken: OSError(65, 'No route to host')", OSError(65, 'No route to host'))

---
--> Failed: ("Connection broken: OSError(65, 'No route to host')", OSError(65, 'No route to host'))
Installation failed: ("Connection broken: OSError(65, 'No route to host')", OSError(65, 'No route to host'))
[STAGE 2/6: Download contents - 33%]
--> Restoring SD-card device (/dev/disk7) mode
Call: ['/usr/bin/osascript', '-e', 'do shell script "chmod -v 0660 /dev/disk7 2>&1" with administrator privileges']
/dev/disk7

*** DURATIONS SUMMARY ***
[1/6] Retrieve Master Image: 21 minutes and 36.6 seconds (Sun Sep  9 08:39:16 2018 to Sun Sep  9 09:00:52 2018)
[2/6] Download contents: 3 hours, 32 minutes and 0.61 seconds (Sun Sep  9 09:00:52 2018 to Sun Sep  9 12:32:53 2018)
TOTAL: 3 hours, 53 minutes and 42.61 seconds (Sun Sep  9 08:39:10 2018 to Sun Sep  9 12:32:53 2018)

```

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 15:35

Hum, very same file and percentage as #222…

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Sep 11, 2018, 15:35

Great :) Then this is a duplicate.

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Sep 11, 2018, 15:36

closed

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 15:36

Can you try and give us the mirror you are hitting? `wiki.mirror.tn` for me at the moment from Mali.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 15:37

reopened

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 15:37

The other one was more generic to download robustness. Let's keep this one open for this very specific download issue until we narrow it down.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 15:40

For the record, that's https://mirrors.dotsrc.org/kiwix/zim/wikisource/wikisource_fr_all_novid_2018-06.zim

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 17:33

OK apparently it was a mistake (@Kelson42 copy-pasted the old log).Please open a new issue for your ansible bug.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 11, 2018, 17:33

closed
