### ISSUE TITLE
Error connecting to QEMU via SSH on Linux

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#251]
In GitLab by @Kelson42 on Sep 13, 2018, 14:44

Version: 2.0-rc8

```
S
ee 'systemctl status kiwix-server.service' for details.



[[0;32m  O
K  [0m] Started Authorization Manager.



[[
0;32m  OK  [0m] Started Modem Manager.



[
[0;32m  OK  [0m] Started Network Manager.



[[
0;32m  OK  [0m] Reached target Network.



[
[0;32m  OK  [0m] Started Launch hostapd.



  
       Starting dnsmasq - A lightweight DHCP and caching DNS server...



  
       Starting OpenBSD Secure Shell server...



  
       Starting Permit User Sessions...



  
       Starting A high performance web server and a reverse proxy server...



 
        Starting Network Manager Wait Online...



[[
0;32m  OK  [0m] Started Permit User Sessions.



         Sta
rting Terminate Plymouth Boot Screen...



  
       Starting Hold until boot process finishes up...



         Sta
rting Network Manager Script Dispatcher Service...






R
a
s
pb
ia
n
 G
NU
/L
in
u
x 9
 
w
ikifundi.hotspot
 ttyAMA0


w
ikifundi 
login: 
p
i



Passwo
rd: 



Last 
login: Thu Sep 13 15:16:13 CEST 2018 on ttyAMA0

Lin
ux wikifundi.hotspot 4.10.0 #1 SMP Fri May 18 11:38:47 UTC 2018 armv7l



The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linu
x comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.




SSH is enabl
ed and the default password for the 'pi' user has not been changed.

T
his is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.




pi
@wikifundi:~$ 
s
udo systemctl
 s
tart ssh;
 e
xit


logout





R
a
sp
bi
an
 GN
U/
Lin
ux
 9
 
w
ikifundi.hotspot
 ttyAMA0


w
ikifundi 
logi
n: 
--> Failed: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Installation failed: Error reading SSH protocol banner[Errno 104] Connection reset by peer
[STAGE 5/6: Post-process contents (virtualized) - 83%]

--- Exception Trace ---
Traceback (most recent call last):
  File "site-packages/paramiko/transport.py", line 1893, in _check_banner
  File "site-packages/paramiko/packet.py", line 331, in readline
  File "site-packages/paramiko/packet.py", line 485, in _read_timeout
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_installation.py", line 278, in run_installation
  File "backend/qemu.py", line 138, in __enter__
  File "backend/qemu.py", line 262, in _boot
  File "site-packages/paramiko/client.py", line 338, in connect
  File "site-packages/paramiko/transport.py", line 500, in start_client
  File "site-packages/paramiko/transport.py", line 1749, in run
  File "site-packages/paramiko/transport.py", line 1897, in _check_banner
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

---
Restoring system sleep policy
Resuming xdg-screensaver (wid #0x4600000)
Call: ['/usr/bin/xdg-screensaver', 'resume', '0x4600000']
xdg-screensaver: Window 0x4600000 does not exist

--> Restoring loop device (/dev/loop2) mode
Call: ['pkexec', 'chmod', '-v', '0660', '/dev/loop2']
mode of '/dev/loop2' changed from 0666 (rw-rw-rw-) to 0660 (rw-rw----)

--> Restoring SD-card device (/dev/sde) mode
Call: ['pkexec', 'chmod', '-v', '0660', '/dev/sde']
mode of '/dev/sde' changed from 0666 (rw-rw-rw-) to 0660 (rw-rw----)

*** DURATIONS SUMMARY ***
[1/6] Retrieve Master Image: 2 minutes and 34.53 seconds (Do 13 Sep 2018 15:05:34  to Do 13 Sep 2018 15:08:08 )
[2/6] Download contents: 6 minutes and 23.82 seconds (Do 13 Sep 2018 15:08:08  to Do 13 Sep 2018 15:14:32 )
[3/6] Image configuration (virtualized): 32 minutes and 52.4 seconds (Do 13 Sep 2018 15:14:32  to Do 13 Sep 2018 15:47:25 )
[4/6] Copy contents onto image: 14 minutes and 27 seconds (Do 13 Sep 2018 15:47:25  to Do 13 Sep 2018 16:01:52 )
[5/6] Post-process contents (virtualized): 1 minute and 46.35 seconds (Do 13 Sep 2018 16:01:52  to Do 13 Sep 2018 16:03:38 )
TOTAL: 58 minutes and 8.37 seconds (Do 13 Sep 2018 15:05:30  to Do 13 Sep 2018 16:03:38 )
```

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 13, 2018, 14:53

changed title from **{-installation failed on linux with rc8-}** to **{+Error connecting to QEMU via SSH on Linux+}**

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 13, 2018, 14:53

changed the description

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 13, 2018, 15:32

I've encountered this as well. For me it was on Stage 3 (yours is step 5). Retried and it worked so it's not systematic.

I think it appeared after [merging the new captive portal](794338642276272fc7e8874949c53479b3234313)

* clear_iptables: task ran every 15mn instead of 5mn. UNRELATED
* Captive portal port moved from 82 to 80 default. UNRELATED
* progress logging fixes. UNRELATED
* captive portal UI. UNRELATED
* New script [pibox-mode-switcher](https://framagit.org/ideascube/pibox-installer/blob/master/ansiblecube/roles/captive_portal/files/pibox-mode-switcher) ran on every NetworkManager events and every 5mn. **MAYBE**
  * tests internet connection (timeout after 2s)
  * restarts dnsmasq if connectivity status changed
* specific DHCP on eth0 connection (`nmcli connection add ifname eth0 type ethernet autoconnect yes save yes`) **MAYBE**
* dnsmasq.conf now serves DNS to `eth0` but excludes `eth0` of DHCP. **MAYBE**
* fixed `enable_service` and `disable_service` includes so any of those statements now apply. **MAYBE**

For the record, within QEMU, the connection we use to communication is on `eth0`.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 13, 2018, 15:33

In addition to finding the cause of this bug, we will also add some retries to SSH connect as it is crucial for pibox to connect and some external factors might disturb it.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 13, 2018, 17:05

OK I am confident this is linked to our dispatcher script for NetworkManager.

Removing it from NetworkManager (as it is already run by cron), adding a `@reboot` entry to catch-up start and making sure dnsmasq is not started until we seal the image (this is not related to this issue but it prevents internet from working within qemu so it should be avoided).

recreating a new master to test…

@Kelson42 please if you have any clue on how to reproduce or if you have a machine where it happens frequently, let me know so we can test it.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 13, 2018, 17:05

mentioned in commit c76623488c7fc68996a8288c0cd14a84763f0890

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Sep 13, 2018, 17:39

@rgaudin I try to reproduce it... Simply make a new release and lets try it.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 14, 2018, 08:31

@Kelson42 here's a new version with the updated master: [i228](http://tmp.kiwix.org/ci/kiwix-plug_installer-linux-i228.tar.gz)

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 17, 2018, 08:28

mentioned in commit 8b3a92ca67645263013d1abdba1d1a463218afd1

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 24, 2018, 15:26

Seems to have been resolved. Closing for now.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 24, 2018, 15:26

closed
