### ISSUE TITLE
Apparent problem to setup password

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#255]
In GitLab by @Kelson42 on Sep 17, 2018, 14:34

With Wikifundi FR max preset:

```
--> wikifundi_content : move wikifundi database
[STAGE 5/6: Post-process contents (virtualized) - 78%]
task path: /var/lib/ansible/local/roles/wikifundi_content/tasks/main.yml:52
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774 `" && echo ansible-tmp-1537190800.6-173739792758774="` echo /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<localhost> PUT /root/.ansible/tmp/ansible-local-2442zYLUMd/tmppX7jZj TO /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774/ /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774/command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1537190800.6-173739792758774/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item=fr) => {
    "changed": true, 
    "cmd": [
        "mv", 
        "/data/wikifundi_langpack_fr/mw_wikifundi_fr.sqlite", 
        "/data/wikifundi/mw_wikifundi_fr.sqlite"
    ], 
    "delta": "0:00:00.159615", 
    "end": "2018-09-17 15:26:46.213498", 
    "invocation": {
        "module_args": {
            "_raw_params": "mv /data/wikifundi_langpack_fr/mw_wikifundi_fr.sqlite /data/wikifundi/mw_wikifundi_fr.sqlite", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "item": "fr", 
    "rc": 0, 
    "start": "2018-09-17 15:26:46.053883", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}

TASK [wikifundi_content : Add admin account to Wikifundi] **********************
--> wikifundi_content : Add admin account to Wikifundi
[STAGE 5/6: Post-process contents (virtualized) - 78%]
task path: /var/lib/ansible/local/roles/wikifundi_content/tasks/main.yml:57
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918 `" && echo ansible-tmp-1537190812.0-120532318292918="` echo /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<localhost> PUT /root/.ansible/tmp/ansible-local-2442zYLUMd/tmpcR0BwP TO /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918/ /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'ADMIN_ACCOUNT=admin ADMIN_PASSWORD=adminadmin WIKIFUNDI_LANG=fr /usr/bin/python /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1537190812.0-120532318292918/ > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item=fr) => {
    "changed": true, 
    "cmd": [
        "php", 
        "maintenance/createAndPromote.php", 
        "--bureaucrat", 
        "--sysop", 
        "--force", 
        "$ADMIN_ACCOUNT", 
        "$ADMIN_PASSWORD"
    ], 
    "delta": "0:00:49.324646", 
    "end": "2018-09-17 15:27:46.593862", 
    "invocation": {
        "module_args": {
            "_raw_params": "php maintenance/createAndPromote.php --bureaucrat --sysop --force \"$ADMIN_ACCOUNT\" \"$ADMIN_PASSWORD\"", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": "/var/www/wikifundi/w", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "item": "fr", 
    "msg": "non-zero return code", 
    "rc": 255, 
    "start": "2018-09-17 15:26:57.269216", 
    "stderr": "Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information.", 
    "stderr_lines": [
        "Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information."
    ], 
    "stdout": "", 
    "stdout_lines": []
}

RUNNING HANDLER [restart uwsgi] ************************************************

RUNNING HANDLER [restart kiwix] ************************************************
	to retry, use: --limit @/var/lib/ansible/local/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=36   changed=21   unreachable=0    failed=1   

STDERR:  [WARNING]: Consider using the unarchive module rather than running tar.  If
STDERR: you need to use command because unarchive is insufficient you can add
STDERR: warn=False to this command task or set command_warnings=False in ansible.cfg to
STDERR: get rid of this message.
sudo sync
sudo shutdown -P 0
STDERR: Shutdown scheduled for Mon 2018-09-17 15:27:50 CEST, use 'shutdown -c' to cancel.
VM is off.

--- Exception Trace ---
Traceback (most recent call last):
  File "run_installation.py", line 280, in run_installation
  File "backend/ansiblecube.py", line 167, in run_phase_two
  File "backend/ansiblecube.py", line 61, in run
  File "backend/qemu.py", line 345, in exec_cmd
backend.qemu.QemuException: ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook -vvv --inventory hosts --tags move-content,seal --extra-vars="@/var/lib/ansible/local/extra_vars.json" main.yml'

---
Restoring system sleep policy
Resuming xdg-screensaver (wid #0x5c00000)
--> Failed: ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook -vvv --inventory hosts --tags move-content,seal --extra-vars="@/var/lib/ansible/local/extra_vars.json" main.yml'
Installation failed: ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook -vvv --inventory hosts --tags move-content,seal --extra-vars="@/var/lib/ansible/local/extra_vars.json" main.yml'
[STAGE 5/6: Post-process contents (virtualized) - 83%]
Call: ['/usr/bin/xdg-screensaver', 'resume', '0x5c00000']
--> Restoring loop device (/dev/loop0) mode
Call: ['pkexec', 'chmod', '-v', '0660', '/dev/loop0']
mode of '/dev/loop0' changed from 0666 (rw-rw-rw-) to 0660 (rw-rw----)

--> Restoring SD-card device (/dev/sdc) mode
Call: ['pkexec', 'chmod', '-v', '0660', '/dev/sdc']
mode of '/dev/sdc' changed from 0666 (rw-rw-rw-) to 0660 (rw-rw----)

*** DURATIONS SUMMARY ***
[1/6] Retrieve Master Image: 3 minutes and 51.02 seconds (Mon 17 Sep 2018 11:28:30  to Mon 17 Sep 2018 11:32:21 )
[2/6] Download contents: 1 hour, 10 minutes and 34.73 seconds (Mon 17 Sep 2018 11:32:21  to Mon 17 Sep 2018 12:42:55 )
[3/6] Image configuration (virtualized): 50 minutes and 18.92 seconds (Mon 17 Sep 2018 12:42:55  to Mon 17 Sep 2018 13:33:14 )
[4/6] Copy contents onto image: 15 minutes and 39.44 seconds (Mon 17 Sep 2018 13:33:14  to Mon 17 Sep 2018 13:48:54 )
[5/6] Post-process contents (virtualized): 1 hour, 39 minutes and 42.36 seconds (Mon 17 Sep 2018 13:48:54  to Mon 17 Sep 2018 15:28:36 )
TOTAL: 4 hours and 13.22 seconds (Mon 17 Sep 2018 11:28:23  to Mon 17 Sep 2018 15:28:36 )
```

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Sep 17, 2018, 15:25

closed via commit f51a3934d6742c34987a2441c55f5f41b56112f3
