### ISSUE TITLE
Impossible to close pibox-installer after successfull installing process

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#29]
In GitLab by @Kelson42 on Jul 2, 2017, 05:05

* Clicking on "Copy log" blocks the whole UI thred for 30s.
* Clicking on "Close" blocks the whole UI indefinitely and the app does not close.

On the output console we see:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 920, in _bootstrap_inner
  File "threading.py", line 868, in run
  File "backend/qemu.py", line 134, in cancel_management
  File "subprocess.py", line 1691, in kill
  File "subprocess.py", line 1681, in send_signal
ProcessLookupError: [Errno 3] No such process
```

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Jul 2, 2017, 05:10

changed the description

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Jul 2, 2017, 05:11

changed the description

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 3, 2017, 15:06

I made some changes on cancel event so thread exception should not happend in d8ff398f4a99fb2c4f555571cdacfbdf47b850aa

But and don't know why Copy log was so slow.

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Jul 4, 2017, 05:09

With last nightly:
* Windows can close
* pibox-installer process still runs at 100%
* no error message on the console
* qemu process is not there anymore

After maybe 20s, the pibox-installer process stops too on its own.

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Jul 4, 2017, 05:59

"Abort" button seems to work fine (at least at the time I have clicked on it).

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Jul 12, 2017, 16:37

I propose to close that issue, it basically works.

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 13, 2017, 07:34

closed
