### ISSUE TITLE
2.0 fails on MacOS

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#332]
In GitLab by @Kelson42 on Nov 20, 2018, 16:34

```
RUNNING HANDLER [restart nginx] ************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874 `" && echo ansible-tmp-1542703959.8-22455428407874="` echo /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/systemd.py
<localhost> PUT /root/.ansible/tmp/ansible-local-2404giO83r/tmpQEciJE TO /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874/systemd.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874/ /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1542703959.8-22455428407874/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "enabled": true, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": true, 
            "force": null, 
            "masked": null, 
            "name": "nginx", 
            "no_block": false, 
            "state": "restarted", 
            "user": false
        }
    }, 
    "name": "nginx", 
    "state": "started", 
    "status": {
        "ActiveEnterTimestamp": "Tue 2018-11-20 08:03:39 CET", 
        "ActiveEnterTimestampMonotonic": "112979651", 
        "ActiveExitTimestampMonotonic": "0", 
        "ActiveState": "active", 
        "After": "system.slice basic.target network.target systemd-journald.socket sysinit.target", 
        "AllowIsolate": "no", 
        "AmbientCapabilities": "0", 
        "AssertResult": "yes", 
        "AssertTimestamp": "Tue 2018-11-20 08:03:26 CET", 
        "AssertTimestampMonotonic": "100005019", 
        "Before": "multi-user.target shutdown.target", 
        "BlockIOAccounting": "no", 
        "BlockIOWeight": "18446744073709551615", 
        "CPUAccounting": "no", 
        "CPUQuotaPerSecUSec": "infinity", 
        "CPUSchedulingPolicy": "0", 
        "CPUSchedulingPriority": "0", 
        "CPUSchedulingResetOnFork": "no", 
        "CPUShares": "18446744073709551615", 
        "CPUUsageNSec": "18446744073709551615", 
        "CPUWeight": "18446744073709551615", 
        "CanIsolate": "no", 
        "CanReload": "yes", 
        "CanStart": "yes", 
        "CanStop": "yes", 
        "CapabilityBoundingSet": "18446744073709551615", 
        "ConditionResult": "yes", 
        "ConditionTimestamp": "Tue 2018-11-20 08:03:26 CET", 
        "ConditionTimestampMonotonic": "100005004", 
        "Conflicts": "shutdown.target", 
        "ControlGroup": "/system.slice/nginx.service", 
        "ControlPID": "0", 
        "DefaultDependencies": "yes", 
        "Delegate": "no", 
        "Description": "A high performance web server and a reverse proxy server", 
        "DevicePolicy": "auto", 
        "Documentation": "man:nginx(8)", 
        "DynamicUser": "no", 
        "ExecMainCode": "0", 
        "ExecMainExitTimestampMonotonic": "0", 
        "ExecMainPID": "1672", 
        "ExecMainStartTimestamp": "Tue 2018-11-20 08:03:39 CET", 
        "ExecMainStartTimestampMonotonic": "112979006", 
        "ExecMainStatus": "0", 
        "ExecReload": "{ path=/usr/sbin/nginx ; argv[]=/usr/sbin/nginx -g daemon on; master_process on; -s reload ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }", 
        "ExecStart": "{ path=/usr/sbin/nginx ; argv[]=/usr/sbin/nginx -g daemon on; master_process on; ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }", 
        "ExecStartPre": "{ path=/usr/sbin/nginx ; argv[]=/usr/sbin/nginx -t -q -g daemon on; master_process on; ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }", 
        "ExecStop": "{ path=/sbin/start-stop-daemon ; argv[]=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }", 
        "FailureAction": "none", 
        "FileDescriptorStoreMax": "0", 
        "FragmentPath": "/lib/systemd/system/nginx.service", 
        "GID": "4294967295", 
        "GuessMainPID": "yes", 
        "IOAccounting": "no", 
        "IOScheduling": "0", 
        "IOWeight": "18446744073709551615", 
        "Id": "nginx.service", 
        "IgnoreOnIsolate": "no", 
        "IgnoreSIGPIPE": "yes", 
        "InactiveEnterTimestampMonotonic": "0", 
        "InactiveExitTimestamp": "Tue 2018-11-20 08:03:26 CET", 
        "InactiveExitTimestampMonotonic": "100057489", 
        "InvocationID": "ed31c1de47e54991a01172ee92682154", 
        "JobTimeoutAction": "none", 
        "JobTimeoutUSec": "infinity", 
        "KillMode": "mixed", 
        "KillSignal": "15", 
        "LimitAS": "18446744073709551615", 
        "LimitASSoft": "18446744073709551615", 
        "LimitCORE": "18446744073709551615", 
        "LimitCORESoft": "0", 
        "LimitCPU": "18446744073709551615", 
        "LimitCPUSoft": "18446744073709551615", 
        "LimitDATA": "18446744073709551615", 
        "LimitDATASoft": "18446744073709551615", 
        "LimitFSIZE": "18446744073709551615", 
        "LimitFSIZESoft": "18446744073709551615", 
        "LimitLOCKS": "18446744073709551615", 
        "LimitLOCKSSoft": "18446744073709551615", 
        "LimitMEMLOCK": "65536", 
        "LimitMEMLOCKSoft": "65536", 
        "LimitMSGQUEUE": "819200", 
        "LimitMSGQUEUESoft": "819200", 
        "LimitNICE": "0", 
        "LimitNICESoft": "0", 
        "LimitNOFILE": "4096", 
        "LimitNOFILESoft": "1024", 
        "LimitNPROC": "14124", 
        "LimitNPROCSoft": "14124", 
        "LimitRSS": "18446744073709551615", 
        "LimitRSSSoft": "18446744073709551615", 
        "LimitRTPRIO": "0", 
        "LimitRTPRIOSoft": "0", 
        "LimitRTTIME": "18446744073709551615", 
        "LimitRTTIMESoft": "18446744073709551615", 
        "LimitSIGPENDING": "14124", 
        "LimitSIGPENDINGSoft": "14124", 
        "LimitSTACK": "18446744073709551615", 
        "LimitSTACKSoft": "8388608", 
        "LoadState": "loaded", 
        "MainPID": "1672", 
        "MemoryAccounting": "no", 
        "MemoryCurrent": "18446744073709551615", 
        "MemoryDenyWriteExecute": "no", 
        "MemoryHigh": "18446744073709551615", 
        "MemoryLimit": "18446744073709551615", 
        "MemoryLow": "0", 
        "MemoryMax": "18446744073709551615", 
        "MemorySwapMax": "18446744073709551615", 
        "MountFlags": "0", 
        "NFileDescriptorStore": "0", 
        "Names": "nginx.service", 
        "NeedDaemonReload": "no", 
        "Nice": "0", 
        "NoNewPrivileges": "no", 
        "NonBlocking": "no", 
        "NotifyAccess": "none", 
        "OOMScoreAdjust": "0", 
        "OnFailureJobMode": "replace", 
        "PIDFile": "/run/nginx.pid", 
        "PermissionsStartOnly": "no", 
        "Perpetual": "no", 
        "PrivateDevices": "no", 
        "PrivateNetwork": "no", 
        "PrivateTmp": "no", 
        "PrivateUsers": "no", 
        "ProtectControlGroups": "no", 
        "ProtectHome": "no", 
        "ProtectKernelModules": "no", 
        "ProtectKernelTunables": "no", 
        "ProtectSystem": "no", 
        "RefuseManualStart": "no", 
        "RefuseManualStop": "no", 
        "RemainAfterExit": "no", 
        "RemoveIPC": "no", 
        "Requires": "system.slice sysinit.target", 
        "Restart": "no", 
        "RestartUSec": "100ms", 
        "RestrictNamespace": "2114060288", 
        "RestrictRealtime": "no", 
        "Result": "success", 
        "RootDirectoryStartOnly": "no", 
        "RuntimeDirectoryMode": "0755", 
        "RuntimeMaxUSec": "infinity", 
        "SameProcessGroup": "no", 
        "SecureBits": "0", 
        "SendSIGHUP": "no", 
        "SendSIGKILL": "yes", 
        "Slice": "system.slice", 
        "StandardError": "inherit", 
        "StandardInput": "null", 
        "StandardOutput": "journal", 
        "StartLimitAction": "none", 
        "StartLimitBurst": "5", 
        "StartLimitIntervalSec": "10000000", 
        "StartupBlockIOWeight": "18446744073709551615", 
        "StartupCPUShares": "18446744073709551615", 
        "StartupCPUWeight": "18446744073709551615", 
        "StartupIOWeight": "18446744073709551615", 
        "StateChangeTimestamp": "Tue 2018-11-20 08:03:39 CET", 
        "StateChangeTimestampMonotonic": "112979651", 
        "StatusErrno": "0", 
        "StopWhenUnneeded": "no", 
        "SubState": "running", 
        "SyslogFacility": "3", 
        "SyslogLevel": "6", 
        "SyslogLevelPrefix": "yes", 
        "SyslogPriority": "30", 
        "SystemCallErrorNumber": "0", 
        "TTYReset": "no", 
        "TTYVHangup": "no", 
        "TTYVTDisallocate": "no", 
        "TasksAccounting": "yes", 
        "TasksCurrent": "18446744073709551615", 
        "TasksMax": "4915", 
        "TimeoutStartUSec": "1min 30s", 
        "TimeoutStopUSec": "5s", 
        "TimerSlackNSec": "50000", 
        "Transient": "no", 
        "Type": "forking", 
        "UID": "4294967295", 
        "UMask": "0022", 
        "UnitFilePreset": "enabled", 
        "UnitFileState": "enabled", 
        "UtmpMode": "init", 
        "WantedBy": "multi-user.target", 
        "WatchdogTimestamp": "Tue 2018-11-20 08:03:39 CET", 
        "WatchdogTimestampMonotonic": "112979630", 
        "WatchdogUSec": "0"
    }
}

RUNNING HANDLER [restart uwsgi] ************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715 `" && echo ansible-tmp-1542703989.43-219585184273715="` echo /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/systemd.py
<localhost> PUT /root/.ansible/tmp/ansible-local-2404giO83r/tmphBc7E2 TO /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715/systemd.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715/ /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1542703989.43-219585184273715/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": true, 
            "force": null, 
            "masked": null, 
            "name": "uwsgi", 
            "no_block": false, 
            "state": "restarted", 
            "user": false
        }
    }, 
    "msg": "Unable to restart service uwsgi: Job for uwsgi.service failed because the control process exited with error code.\nSee \"systemctl status uwsgi.service\" and \"journalctl -xe\" for details.\n"
}

RUNNING HANDLER [restart kiwix] ************************************************
META: ran handlers

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/var/lib/ansible/local/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=62   changed=35   unreachable=0    failed=1   

STDERR:  [WARNING]: Consider using the unarchive module rather than running tar.  If
STDERR: you need to use command because unarchive is insufficient you can add
STDERR: warn=False to this command task or set command_warnings=False in ansible.cfg to
STDERR: get rid of this message.
sudo sync
sudo shutdown -P 0
STDERR: Shutdown scheduled for Tue 2018-11-20 09:55:15 CET, use 'shutdown -c' to cancel.
VM is off.

--- Exception Trace ---
Traceback (most recent call last):
  File "run_installation.py", line 331, in run_installation
  File "backend/ansiblecube.py", line 218, in run_phase_two
  File "backend/ansiblecube.py", line 75, in run
  File "backend/qemu.py", line 419, in exec_cmd
backend.qemu.QemuException: ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook -vvv --inventory hosts --tags move-content,seal --extra-vars="@/var/lib/ansible/local/extra_vars.json" main.yml'

---
Restoring system sleep policy
Stopping caffeinate process #607
--> Failed: ssh command failed with status
Installation failed: ssh command failed with status 2. cmd: sudo sh -c 'cd /var/lib/ansible/local && /usr/local/bin/ansible-playbook -vvv --inventory hosts --tags move-content,seal --extra-vars="@/var/lib/ansible/local/extra_vars.json" main.yml'
[STAGE 5/6: Post-process contents (virtualized) - 83%]
*** DURATIONS SUMMARY ***
[1/6] Retrieve Master Image: 51.45 seconds (Tue Nov 20 06:42:50 2018 to Tue Nov 20 06:43:41 2018)
[2/6] Download contents: 3 minutes and 43.42 seconds (Tue Nov 20 06:43:41 2018 to Tue Nov 20 06:47:25 2018)
[3/6] Image configuration (virtualized): 50 minutes and 26.33 seconds (Tue Nov 20 06:47:25 2018 to Tue Nov 20 07:37:51 2018)
[4/6] Copy contents onto image: 23 minutes and 56.06 seconds (Tue Nov 20 07:37:51 2018 to Tue Nov 20 08:01:47 2018)
[5/6] Post-process contents (virtualized): 1 hour, 57 minutes and 5.64 seconds (Tue Nov 20 08:01:47 2018 to Tue Nov 20 09:58:53 2018)
TOTAL: 3 hours, 16 minutes and 2.91 seconds (Tue Nov 20 06:42:50 2018 to Tue Nov 20 09:58:53 2018)
```

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Nov 20, 2018, 16:36

Please submit the complete log as the failing info is not present here.

**Comment by rgaudin** [comment]
Missing failing info. Closing.
