### ISSUE TITLE
Using new version of Kiwix Hotspot, image creation failed three times.

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#405]
In GitLab by @wwwhtml on Jun 3, 2019, 09:22

Hello Folks, I opened this issue, but I think I am not going to need help. I just ordered a couple images 
from the website. 

The issue:
I locally have created other images before with the previous Kiwix Hotspot version, but now that I am using the new one I got three failed attempts. 

Anyhow, I am providing the information that I collected in case you get someone else having similar issue.

I am attaching:
1. A log file output. 
2. An screenshot showing the error and the files used (cache).
3. An additional screenshot showing a gateway error. 
This second screenshot shows the gateway error was generated from a Kiwix Hotspot that was made from an errored Kiwix image, and the balenaEtcher flashing utility.

Thank you!

[Screen_Shot_2019-06-02_at_5.34.54_PM](/uploads/c0463aa180e511165c79616110cf7d5e/Screen_Shot_2019-06-02_at_5.34.54_PM.png.

[Screen_Shot_2019-06-02_at_7.28.37_PM](/uploads/7f5e667dabdb8d45dceb2df28dc3b82c/Screen_Shot_2019-06-02_at_7.28.37_PM.png)

[copy-paste-for-kiwix-dev.txt](/uploads/62df74e969442801f5fe3d403540e139/copy-paste-for-kiwix-dev.txt)![Screen_Shot_2019-06-03_at_1.55.19_AM](/uploads/36649bad518a7dde4cd6335af68fbef3/Screen_Shot_2019-06-03_at_1.55.19_AM.png)![Screen_Shot_2019-06-02_at_5.34.54_PM](/uploads/be26d1a1ff6e89365ef3144c5443a3fb/Screen_Shot_2019-06-02_at_5.34.54_PM.png)

**Comment by rgaudin** [comment]
In GitLab by @wwwhtml on Jun 3, 2019, 09:23

changed the description

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Jun 4, 2019, 09:09

Thanks @wwwhtml. Erroneous builds are not expected to work and should not be flashed :)

Unfortunately, the error message in your log is not that helpful (`Input/output error`).

It comes from the KALite setup script.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/venvs/kalite/lib/python2.7/site-packages/kalite/__main__.py", line 7, in <module>
    main()
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/cli.py", line 872, in main
    manage(command, args=arguments['DJANGO_OPTIONS'])
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/cli.py", line 410, in manage
    utility.execute()
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/packages/bundled/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/user/venvs/kalite/local/lib/python2.7/site-packages/kalite/project/settings/default.py", line 14, in <module>
    "# This is the default location where the kalite command finds its settings"
IOError: [Errno 5] Input/output error
```

I'll try to run it myself to see if I can reproduce it.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Jun 5, 2019, 15:03

Ran it with FR and it failed exactly the same way. investigating.

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Jun 5, 2019, 17:40

closed via commit b44796890d2c1921630e38688bb23dbfc5120748

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Jun 7, 2019, 12:15

btw @wwwhtml, in your message you mention the fact that EN and FR are the only two available language options now.

It's true but this `language` setting was used only for `ideascube` (homepage manager) which has been removed.

There's no UI to apply language to so, in practice, it doesn't change anything. It just customizes some content descriptions (for which ES was never implemented).

**Comment by rgaudin** [comment]
In GitLab by @rgaudin on Jun 7, 2019, 16:10

Please retry with [2.0.5](http://download.kiwix.org/release/kiwix-hotspot/v2.0.5/)
