### ISSUE TITLE
Last version of pibox-installer for linux crashs at start on Ubuntu 16.04

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#49]
In GitLab by @Kelson42 on Jul 8, 2017, 06:47

```
$ ./pibox-installer 
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "gui.py", line 448, in <module>
  File "gui.py", line 159, in __init__
  File "site-packages/langcodes/__init__.py", line 594, in language_name
  File "site-packages/langcodes/__init__.py", line 554, in _get_name
  File "site-packages/langcodes/names.py", line 96, in code_to_names
  File "site-packages/langcodes/names.py", line 35, in load_trie
  File "src/marisa_trie.pyx", line 218, in marisa_trie._Trie.load (src/marisa_trie.cpp:4903)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIfJc9VW/langcodes/data/trie/language_to_name.marisa'
Failed to execute script __main__
```

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 10, 2017, 08:04

mentioned in commit 5846ea83a600ebc1ad92880e8e5bbeeb141d9f91

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 10, 2017, 08:17

closed
