### ISSUE TITLE
mkfs fails to format data partition on Linux

### ISSUE THREAD

**Issue by VerstreuteSeele** [kiwix/kiwix-hotspot#533]
Installed as described on your page. Using a good quality 32GB micro-sd Card and newest version of ubuntu
Everything works fine: Downloads Master Image, Downlaods data, everything... until this:

Failed: Process ['/sbin/mkfs.exfat', '-n', 'HSPOT_DATA', '
Installation failed: Process ['/sbin/mkfs.exfat', '-n', 'HSPOT_DATA', '/dev/loop15'] failed

--- Exception Trace ---
Traceback (most recent call last):
  File "run_installation.py", line 329, in run_installation
  File "backend/mount.py", line 396, in format_data_partition
  File "backend/util.py", line 110, in subprocess_pretty_check_call
  File "backend/util.py", line 102, in subprocess_pretty_call
backend.util.CheckCallException: Process ['/sbin/mkfs.exfat', '-n', 'HSPOT_DATA', '/dev/loop15'] failed

---
[16:19:16] Restoring system sleep policy
[16:19:16] Resuming xdg-screensaver (wid #0x6600000)
[16:19:16] Call: ['/usr/bin/xdg-screensaver', 'resume', '0x6600000']
[16:19:16] xdg-screensaver: Window 0x6600000 does not exist

[16:19:16] --> Restoring loop device (/dev/loop15) mode
[16:19:16] Call: ['pkexec', 'chmod', '-v', '0660', '/dev/loop15']
[16:28:12] mode of '/dev/loop15' changed from 0666 (rw-rw-rw-) to 0660 (rw-rw----)

[16:28:12] *** DURATIONS SUMMARY ***
[16:28:12] [1/6] Retrieve Master Image: 2 minutes and 50.3 seconds (So 20 Sep 2020 15:19:13  to So 20 Sep 2020 15:22:03 )
[16:28:12] [2/6] Download contents: 6 minutes and 27.63 seconds (So 20 Sep 2020 15:22:03  to So 20 Sep 2020 15:28:31 )
[16:28:12] [3/6] Image configuration (virtualized): 50 minutes and 36.46 seconds (So 20 Sep 2020 15:28:31  to So 20 Sep 2020 16:19:07 )
[16:28:12] [4/6] Copy contents onto image: 8.8 seconds (So 20 Sep 2020 16:19:07  to So 20 Sep 2020 16:19:16 )
[16:28:12] TOTAL: 1 hour and 12.58 seconds (So 20 Sep 2020 15:19:03  to So 20 Sep 2020 16:19:16 )

**Comment by VerstreuteSeele** [comment]
little update: Worked perfectly fine on windows and I now have a new usecase for my old raspberry pi. 

But i'd still love to figure out why it didnt work on Ubuntu.

**Comment by rgaudin** [comment]
I don't know what went wrong. Here are a few manual steps you could try to input in a terminal so we get a feedback of mkfs.
Please share its output.

```sh
# inside the kiwix-hotspot.cache folder
unzip hotspot-master_2019-08-24.img.zip
 # get the loop device path for data partition : /dev/loopX (once you get it, replace X with number in following commands)
/usr/bin/udisksctl loop-setup --offset 7000031744 --size 755805696 --file hotspot-master_2019-08-24.img --no-user-interaction
# make sure not mounted
/usr/bin/udisksctl unmount --block-device /dev/loopX --no-user-interaction
# change perm
sudo chmod -v o+rw /dev/loopX
# format loop
mkfs_exe -n HSPOT_DATA /dev/loopX
echo $?
# now remove what we did
/usr/bin/udisksctl unmount --block-device" /dev/loopX --no-user-interaction
/usr/bin/udisksctl loop-delete --block-device /dev/loopX --no-user-interaction
rm hotspot-master_2019-08-24.img
```

**Comment by VerstreuteSeele** [comment]
Looks like I found the issue:
Soo.. if I run "mkfs_exe -n HSPOT_DATA /dev/loopX" I get: command not found. 
If however I run just mkfs instead of mkfs_exe I get this error: "mkfs.ext2: invalid blocks '/dev/loop11' on device 'HSPOT_DATA' "

**Comment by rgaudin** [comment]
Sorry it's a typo it should be mkfs.exfat instead of mkfs_exe.
I hope you replaced the X in /dev/loopX in all the commands as well

**Comment by kelson42** [comment]
@rgaudin I fear that without any feedback from @VerstreuteSeele it might be difficult to do anything here?!

**Comment by rgaudin** [comment]
Yes, let's close it.
