### ISSUE TITLE
"Quit" button failing to quit

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-hotspot#597]
Here is what I see on the terminal:
```
(kiwix-hotspot:135790): Gtk-WARNING **: 11:01:25.674: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(kiwix-hotspot:135790): Gtk-WARNING **: 11:01:25.689: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(kiwix-hotspot:135790): Gtk-WARNING **: 11:01:25.708: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(kiwix-hotspot:135790): Gtk-WARNING **: 11:01:25.723: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)
Traceback (most recent call last):
  File "gui.py", line 1348, in run_quit_button_clicked
  File "gui.py", line 1344, in cancel_run
  File "util.py", line 302, in cancel
ProcessLookupError: [Errno 3] No such process
```

**Comment by kelson42** [comment]
Actually I had to kill the process to be able to leave
