### ISSUE TITLE
pibox-installer-linux (nightly) crashing at start on Ubuntu Xenial 64 bits

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#6]
In GitLab by @Kelson42 on May 30, 2017, 19:06

```
$ ./pibox-installer-linux 
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "gui.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "gi/importer.py", line 67, in load_module
  File "gi/module.py", line 294, in _load
  File "gi/module.py", line 273, in get_introspection_module
  File "gi/module.py", line 122, in __init__
gi.RepositoryError: Typelib file for namespace 'xlib', version '2.0' not found
Failed to execute script __main__
```

**Comment by rgaudin** [comment]
In GitLab by @mgautierfr on May 31, 2017, 14:13

assigned to @thiolliere

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jun 2, 2017, 09:11

Thanks for the report

This is a known issue, packaging on linux doesn't work yet.

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jun 15, 2017, 12:40

now it should be OK with  !2
however it uses mgautierfr fork of pyinstaller and this should be merged

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jun 15, 2017, 12:54

closed
