### ISSUE TITLE
Linux crash with last nightly

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-hotspot#80]
In GitLab by @Kelson42 on Jul 22, 2017, 07:05

At pibox-install start...

```
$ ./pibox-installer 
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/travis/virtualenv/python3.4_with_system_site_packages/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "gui.py", line 486, in <module>
  File "gui.py", line 137, in __init__
gi._glib.GError: Couldn't recognize the image file format for file '/tmp/_MEIrbskwU/pibox-installer-logo.png'
Failed to execute script __main__
```

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 24, 2017, 07:55

yes actually binaries for macos and linux are broken since friday.

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 24, 2017, 08:54

done for linux

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 24, 2017, 08:54

closed

**Comment by rgaudin** [comment]
In GitLab by @Kelson42 on Jul 24, 2017, 12:04

@thiolliere What does that mean for the other OSes?

**Comment by rgaudin** [comment]
In GitLab by @thiolliere on Jul 24, 2017, 12:19

now done for macos too.
windows build were OK
